settings:
  visual:
    title: Chess Python
    font: Arial
    textSize: 25
    width: 400
    height: 400
    menuWidth: 150
    icon: images/icon-round.png
  game:
    maxFPS: 120
    logFPS: true
    whiteStarts: true
    blackAndWhiteColor: false
    AI: false
    xGrid: 8
    yGrid: 8