settings:
  visual:
    title: Chess Python
    font: Arial
    textSize: 25
    width: 800
    height: 800
    menuWidth: 200
    icon: images/icon-round.png
  game:
    whiteStarts: true
    blackAndWhiteColor: false
    AI: false
    xGrid: 8
    yGrid: 8